# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BroadcastUpload' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BroadcastUpload

end

target 'BroadcastUploadSetupUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BroadcastUploadSetupUI

end

target 'HelloReplayKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloReplayKit
  pod 'YPImagePicker'

end
